//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaPerfect_ObjectRefWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaPerfect.ObjectRef), typeof(System.Object));
		L.RegFunction("New", _CreateLuaPerfect_ObjectRef);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("objectID", get_objectID, set_objectID);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateLuaPerfect_ObjectRef(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
				LuaPerfect.ObjectRef obj = new LuaPerfect.ObjectRef(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: LuaPerfect.ObjectRef.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_objectID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaPerfect.ObjectRef obj = (LuaPerfect.ObjectRef)o;
			int ret = obj.objectID;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index objectID on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_objectID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaPerfect.ObjectRef obj = (LuaPerfect.ObjectRef)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.objectID = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index objectID on a nil value");
		}
	}
}

