//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaPerfect_ObjectItemWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaPerfect.ObjectItem), typeof(System.Object));
		L.RegFunction("GetChildCount", GetChildCount);
		L.RegFunction("GetChildName", GetChildName);
		L.RegFunction("SetValue", SetValue);
		L.RegFunction("GetValue", GetValue);
		L.RegFunction("AddChild", AddChild);
		L.RegFunction("GetChildObject", GetChildObject);
		L.RegFunction("GetChildObjectByName", GetChildObjectByName);
		L.RegFunction("StaticGetChildCount", StaticGetChildCount);
		L.RegFunction("StaticGetValue", StaticGetValue);
		L.RegFunction("StaticGetChildName", StaticGetChildName);
		L.RegFunction("StaticGetChildObject", StaticGetChildObject);
		L.RegFunction("StaticGetChildObjectByName", StaticGetChildObjectByName);
		L.RegFunction("New", _CreateLuaPerfect_ObjectItem);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("childObjectRefList", get_childObjectRefList, set_childObjectRefList);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateLuaPerfect_ObjectItem(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				LuaPerfect.ObjectItem obj = new LuaPerfect.ObjectItem();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: LuaPerfect.ObjectItem.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetChildCount(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaPerfect.ObjectItem obj = (LuaPerfect.ObjectItem)ToLua.CheckObject<LuaPerfect.ObjectItem>(L, 1);
			int o = obj.GetChildCount();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetChildName(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaPerfect.ObjectItem obj = (LuaPerfect.ObjectItem)ToLua.CheckObject<LuaPerfect.ObjectItem>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			string o = obj.GetChildName(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetValue(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaPerfect.ObjectItem obj = (LuaPerfect.ObjectItem)ToLua.CheckObject<LuaPerfect.ObjectItem>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetValue(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetValue(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaPerfect.ObjectItem obj = (LuaPerfect.ObjectItem)ToLua.CheckObject<LuaPerfect.ObjectItem>(L, 1);
			string o = obj.GetValue();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddChild(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			LuaPerfect.ObjectItem obj = (LuaPerfect.ObjectItem)ToLua.CheckObject<LuaPerfect.ObjectItem>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			object arg1 = ToLua.ToVarObject(L, 3);
			obj.AddChild(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetChildObject(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaPerfect.ObjectItem obj = (LuaPerfect.ObjectItem)ToLua.CheckObject<LuaPerfect.ObjectItem>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			LuaPerfect.ObjectRef o = obj.GetChildObject(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetChildObjectByName(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaPerfect.ObjectItem obj = (LuaPerfect.ObjectItem)ToLua.CheckObject<LuaPerfect.ObjectItem>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaPerfect.ObjectRef o = obj.GetChildObjectByName(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StaticGetChildCount(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaPerfect.ObjectItem arg0 = (LuaPerfect.ObjectItem)ToLua.CheckObject<LuaPerfect.ObjectItem>(L, 1);
			int o = LuaPerfect.ObjectItem.StaticGetChildCount(arg0);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StaticGetValue(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaPerfect.ObjectItem arg0 = (LuaPerfect.ObjectItem)ToLua.CheckObject<LuaPerfect.ObjectItem>(L, 1);
			string o = LuaPerfect.ObjectItem.StaticGetValue(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StaticGetChildName(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaPerfect.ObjectItem arg0 = (LuaPerfect.ObjectItem)ToLua.CheckObject<LuaPerfect.ObjectItem>(L, 1);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 2);
			string o = LuaPerfect.ObjectItem.StaticGetChildName(arg0, arg1);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StaticGetChildObject(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaPerfect.ObjectItem arg0 = (LuaPerfect.ObjectItem)ToLua.CheckObject<LuaPerfect.ObjectItem>(L, 1);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 2);
			LuaPerfect.ObjectRef o = LuaPerfect.ObjectItem.StaticGetChildObject(arg0, arg1);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StaticGetChildObjectByName(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaPerfect.ObjectItem arg0 = (LuaPerfect.ObjectItem)ToLua.CheckObject<LuaPerfect.ObjectItem>(L, 1);
			string arg1 = ToLua.CheckString(L, 2);
			LuaPerfect.ObjectRef o = LuaPerfect.ObjectItem.StaticGetChildObjectByName(arg0, arg1);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_childObjectRefList(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaPerfect.ObjectItem obj = (LuaPerfect.ObjectItem)o;
			System.Collections.Generic.List<LuaPerfect.ObjectRef> ret = obj.childObjectRefList;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index childObjectRefList on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_childObjectRefList(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaPerfect.ObjectItem obj = (LuaPerfect.ObjectItem)o;
			System.Collections.Generic.List<LuaPerfect.ObjectRef> arg0 = (System.Collections.Generic.List<LuaPerfect.ObjectRef>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<LuaPerfect.ObjectRef>));
			obj.childObjectRefList = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index childObjectRefList on a nil value");
		}
	}
}

