-- This file is generated by program!
-- Don't change it manaully.
-- Author: zerospace007@163.com  NormanYang
-- Source file: Config/ConfigAll.lua
-- Created at: Aug 2019



--load require管理名称--
local LoadRq =
{
	 RandomName = require 'Config/RandomName',
	 Sound = require 'Config/Sound',
}

--配置管理名称--
ConfigName =
{
	RandomName = 'RandomName',
	Sound = 'Sound',
}

--配置文件管理--
ConfigAll = {};
local this = ConfigAll;
local configList = {};

--添加所有配置到管理列表--
function ConfigAll.LoadAll()
	   this.AddConfig(ConfigName.RandomName, LoadRq.RandomName);
	   this.AddConfig(ConfigName.Sound, LoadRq.Sound);
end

--添加配置表--
function ConfigAll.AddConfig(configName, configObj)
	configList[configName] = configObj;
end

--获取配置表--
function ConfigAll.GetConfig(configName)
	return configList[configName];
end

--移除配置表--
function ConfigAll.RemoveConfig(configName)
	configList[configName] = nil;
end

return ConfigAll;
