-- This file is generated by program!
-- Don't change it manaully.
-- Author: zerospace007@163.com  NormanYang
-- Source file: 策划表/玩家随机名字.xlsx
-- Created at: Aug 2019


--properties
-- id:int  //  编号
-- adjective:string  //  形容词
-- fname:string  //  姓
-- man:string  //  男名
-- woman:string  //  女名


local data = {}

data[1] = {  id = 1,  adjective = "纯洁的",  fname = "赵",  man = "茂",  woman = "翠丝" }
data[2] = {  id = 2,  adjective = "天真的",  fname = "钱",  man = "州",  woman = "清舒" }
data[3] = {  id = 3,  adjective = "体贴的",  fname = "孙",  man = "阳",  woman = "曼蔓" }
data[4] = {  id = 4,  adjective = "漂亮的",  fname = "李",  man = "安",  woman = "涵柏" }
data[5] = {  id = 5,  adjective = "可爱的",  fname = "周",  man = "睿达",  woman = "若英" }
data[6] = {  id = 6,  adjective = "温柔的",  fname = "吴",  man = "弘新",  woman = "森莉" }
data[7] = {  id = 7,  adjective = "清纯的",  fname = "郑",  man = "宏毅",  woman = "桐欣" }
data[8] = {  id = 8,  adjective = "聪明的",  fname = "王",  man = "俊名",  woman = "惜雪" }
data[9] = {  id = 9,  adjective = "甜美的",  fname = "冯",  man = "雨石",  woman = "平彤" }
data[10] = {  id = 10,  adjective = "乖巧的",  fname = "陈",  man = "高洁",  woman = "锦薇" }
data[11] = {  id = 11,  adjective = "纯真的",  fname = "褚",  man = "彭魄",  woman = "美偲" }
data[12] = {  id = 12,  adjective = "优美的",  fname = "卫",  man = "和玉",  woman = "安祯" }
data[13] = {  id = 13,  adjective = "善良的",  fname = "蒋",  man = "睿识",  woman = "语芙" }
data[14] = {  id = 14,  adjective = "迷人的",  fname = "沈",  man = "英才",  woman = "凝然" }
data[15] = {  id = 15,  adjective = "讨喜的",  fname = "韩",  man = "斌斌",  woman = "源源" }
data[16] = {  id = 16,  adjective = "温和的",  fname = "杨",  man = "成益",  woman = "宛曼" }
data[17] = {  id = 17,  adjective = "无邪的",  fname = "朱",  man = "华茂",  woman = "诗婧" }
data[18] = {  id = 18,  adjective = "秀美的",  fname = "秦",  man = "高朗",  woman = "暄美" }
data[19] = {  id = 19,  adjective = "动人的",  fname = "尤",  man = "文博",  woman = "绣文" }
data[20] = {  id = 20,  adjective = "娇小的",  fname = "许",  man = "昂雄",  woman = "绿夏" }
data[21] = {  id = 21,  adjective = "可人的",  fname = "何",  man = "同光",  woman = "芳懿" }
data[22] = {  id = 22,  adjective = "秀丽的",  fname = "吕",  man = "弘亮",  woman = "迎曼" }
data[23] = {  id = 23,  adjective = "文静的",  fname = "施",  man = "俊哲",  woman = "冬菱" }
data[24] = {  id = 24,  adjective = "百折不挠的",  fname = "张",  man = "俊雅",  woman = "莉莉" }
data[25] = {  id = 25,  adjective = "兼人之勇的",  fname = "孔",  man = "咏思",  woman = "思宸" }
data[26] = {  id = 26,  adjective = "勇往直前的",  fname = "曹",  man = "志业",  woman = "恨云" }
data[27] = {  id = 27,  adjective = "无所畏惧的",  fname = "严",  man = "敏才",  woman = "冷玉" }
data[28] = {  id = 28,  adjective = "临危不惧的",  fname = "华",  man = "翰池",  woman = "彩静" }
data[29] = {  id = 29,  adjective = "奋不顾身的",  fname = "金",  man = "海海",  woman = "梓蓓" }
data[30] = {  id = 30,  adjective = "杀敌致果的",  fname = "魏",  man = "景曜",  woman = "南珍" }
data[31] = {  id = 31,  adjective = "身先士卒的",  fname = "陶",  man = "浩旷",  woman = "沈然" }
data[32] = {  id = 32,  adjective = "大智大勇的",  fname = "姜",  man = "成荫",  woman = "晓兰" }
data[33] = {  id = 33,  adjective = "勇猛果敢的",  fname = "戚",  man = "正志",  woman = "湘君" }
data[34] = {  id = 34,  adjective = "匹马一麾的",  fname = "谢",  man = "高寒",  woman = "悠逸" }
data[35] = {  id = 35,  adjective = "挺身而出的",  fname = "邹",  man = "同甫",  woman = "凌瑶" }
data[36] = {  id = 36,  adjective = "冲锋陷阵的",  fname = "喻",  man = "宏大",  woman = "婷玉" }

return data
