-- This file is generated by program!
-- Don't change it manaully.
-- Author: zerospace007@163.com  NormanYang
-- Source file: 策划表/Sound.xlsx
-- Created at: Aug 2019


--properties
-- Sounds:string  //  资源
-- type:int  //  音频类型
-- mode:int  //  播放模式


local data = {}

data["BgmLogin"] = {  Sounds = "BgmLogin",  type = 1,  mode = 1 }

data["Start"] = {  Sounds = "Start",  type = 2,  mode = 3 }
data["Click"] = {  Sounds = "Click",  type = 2,  mode = 3 }
data["Close"] = {  Sounds = "Close",  type = 2,  mode = 3 }
data["OpenUI"] = {  Sounds = "OpenUI",  type = 2,  mode = 3 }

return data
