-- This file is generated by program!
-- Don't change it manaully.
-- Author: zerospace007@163.com  NormanYang
-- Source file: 策划表/Sound.xlsx
-- Created at: Aug 2019


--properties
-- Sounds:string  //  资源
-- type:int  //  音频类型
-- mode:int  //  播放模式


local data = {}

data["BgmLogin"] = {  Sounds = "BgmLogin",  type = 1,  mode = 1 }
data["BgmBuild"] = {  Sounds = "BgmBuild",  type = 1,  mode = 1 }
data["BgmBuildFeild"] = {  Sounds = "BgmBuildFeild",  type = 2,  mode = 2 }
data["BgmWorld"] = {  Sounds = "BgmWorld",  type = 2,  mode = 2 }
data["BgmBattle"] = {  Sounds = "BgmBattle",  type = 2,  mode = 3 }
data["Start"] = {  Sounds = "Start",  type = 2,  mode = 3 }
data["Click"] = {  Sounds = "Click",  type = 2,  mode = 3 }
data["Close"] = {  Sounds = "Close",  type = 2,  mode = 3 }
data["OpenUI"] = {  Sounds = "OpenUI",  type = 2,  mode = 3 }
data["TalkSend"] = {  Sounds = "TalkSend",  type = 2,  mode = 3 }
data["EquipChange"] = {  Sounds = "EquipChange",  type = 2,  mode = 3 }
data["Promotion"] = {  Sounds = "Promotion",  type = 2,  mode = 3 }
data["ArcherAttack"] = {  Sounds = "ArcherAttack",  type = 2,  mode = 3 }
data["NormalAttack1"] = {  Sounds = "NormalAttack1",  type = 2,  mode = 3 }
data["NormalAttack2"] = {  Sounds = "NormalAttack2",  type = 2,  mode = 3 }
data["NormalShoot"] = {  Sounds = "NormalShoot",  type = 2,  mode = 3 }
data["WeaponShoot1"] = {  Sounds = "WeaponShoot1",  type = 2,  mode = 3 }
data["WeaponShoot2"] = {  Sounds = "WeaponShoot2",  type = 2,  mode = 3 }
data["WeaponAttack1"] = {  Sounds = "WeaponAttack1",  type = 2,  mode = 3 }
data["WeaponAttack2"] = {  Sounds = "WeaponAttack2",  type = 2,  mode = 3 }
data["hero_2010"] = {  Sounds = "hero_2010",  type = 2,  mode = 3 }
data["hero_2011"] = {  Sounds = "hero_2011",  type = 2,  mode = 3 }
data["hero_3006"] = {  Sounds = "hero_3006",  type = 2,  mode = 3 }
data["hero_3007"] = {  Sounds = "hero_3007",  type = 2,  mode = 3 }
data["hero_3008"] = {  Sounds = "hero_3008",  type = 2,  mode = 3 }
data["hero_3009"] = {  Sounds = "hero_3009",  type = 2,  mode = 3 }
data["hero_3010"] = {  Sounds = "hero_3010",  type = 2,  mode = 3 }
data["hero_4001"] = {  Sounds = "hero_4001",  type = 2,  mode = 3 }
data["hero_4002"] = {  Sounds = "hero_4002",  type = 2,  mode = 3 }
data["hero_4003"] = {  Sounds = "hero_4003",  type = 2,  mode = 3 }
data["hero_4004"] = {  Sounds = "hero_4004",  type = 2,  mode = 3 }
data["hero_4005"] = {  Sounds = "hero_4005",  type = 2,  mode = 3 }
data["hero_4006"] = {  Sounds = "hero_4006",  type = 2,  mode = 3 }
data["hero_4007"] = {  Sounds = "hero_4007",  type = 2,  mode = 3 }
data["hero_4008"] = {  Sounds = "hero_4008",  type = 2,  mode = 3 }
data["hero_5001"] = {  Sounds = "hero_5001",  type = 2,  mode = 3 }
data["hero_5002"] = {  Sounds = "hero_5002",  type = 2,  mode = 3 }
data["hero_5003"] = {  Sounds = "hero_5003",  type = 2,  mode = 3 }
data["hero_5004"] = {  Sounds = "hero_5004",  type = 2,  mode = 3 }
data["hero_5005"] = {  Sounds = "hero_5005",  type = 2,  mode = 3 }
data["hero_5006"] = {  Sounds = "hero_5006",  type = 2,  mode = 3 }

return data
